[plancklowres]
git-tree-sha1 = "55aefe5af2a7c81db192de15d553ab00da56ca58"
lazy = true

    [[plancklowres.download]]
    url = "https://github.com/xzackli/PSPipePlanckRender.jl/releases/download/v0.1/plancklowres.tar.gz"
    sha256 = "8e420d81db37d3d2ae93390e927cd20400a08bef018ca8ed81e079bbd3b0f4e7"
